[cosmic-ray]
module-path = "student_management_app/StudentViews.py"
timeout = 60.0
excluded-modules = []
test-command = 'cmd /c C:/cr/run_student_attendance.cmd'

[cosmic-ray.distributor]
name = "local"